import type { Metadata } from 'next';
import { MuiProvider, StateProvider, StyledProvider } from './_providers';

import Nav from '@/components/Nav';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Agnes',
  description: 'Generated by create next app'
};

interface RootLayoutProps {
  children: React.ReactNode;
}
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <MuiProvider>
          <StyledProvider>
            <StateProvider>
              <Nav />
              {children}
              <Footer />
            </StateProvider>
          </StyledProvider>
        </MuiProvider>
      </body>
    </html>
  );
};

export default RootLayout;

